image: docker:latest

services:
  - docker:dind

stages:
  - build api

before_script:
  - docker info
  - echo "$REGISTRY_PWD" | docker login -u "$REGISTRY_USER" --password-stdin

build-api:
  stage: build api
  script:
    - docker build -t justus1994/private ./api
    - docker push justus1994/private
  only:
    - master

