image: docker:latest
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build api

before_script:
  - docker info
  - echo "$REGISTRY_PWD" | docker login -u "$REGISTRY_USER" --password-stdin

build-api:
  stage: build api
  script:
    - docker pull justus1994/private:latest
    - docker build --cache-from justus1994/private:latest -t justus1994/private:latest ./api
    - docker push justus1994/private
  only:
    - master
