image: docker:latest

services:
  - docker:dind

stages:
    - build
    
before_script:
   - docker info


build-master:
  stage: build
  script:
    - echo "$REGISTRY_PWD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker build -t "$REGISTRY_IMAGE" ./api
    - docker push "$REGISTRY_IMAGE" 
  only:
    - master
