image: docker:latest

services:
  - docker:dind

stages:
  - test api
  - build api

  
test-api:
  image: golang:alpine
  stage: test api
  services: 
    - redis:latest
  script:
    - apk update && apk add --no-cache git
    - cd api && go mod download
    - CGO_ENABLED=0 go test
  
build-api:
  stage: build api
  script:
    - docker info
    - echo "$REGISTRY_PWD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker pull justus1994/private:latest || true
    - docker build justus1994/private:latest -t justus1994/private:latest ./api
    - docker push justus1994/private:latest
  only:
    - master

