image: docker:latest
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test-api
  - test-web
  - push

test-api:
  image: golang:alpine
  stage: test-api
  services: 
    - redis:latest
  script:
    - apk update && apk add --no-cache git
    - cd api && go mod download
    - CGO_ENABLED=0 go test

test-web:
  image: node:alpine
  stage: test-web
  script: 
    - cd web && npm install 
    - npm test
    
push-api:
  stage: push
  script:
    - docker info
    - echo "$REGISTRY_PWD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker pull "$REGISTRY_API" || true 
    - docker build --cache-from "$REGISTRY_API" -t "$REGISTRY_API" ./api
    - docker push "$REGISTRY_API"
  only:
    - master
    
push-web:
  stage: push
  script: 
    - docker info
    - echo "$REGISTRY_PWD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker pull "$REGISTRY_WEB" || true
    - docker build --cache-from "$REGISTRY_WEB" -t "$REGISTRY_WEB" ./web
    - docker push "$REGISTRY_WEB"
  only:
    - master
