image: docker:latest

services:
  - docker:dind

stages:
  - build api
  - build client

before_script:
  - docker info
  - echo "$REGISTRY_PWD" | docker login -u "$REGISTRY_USER" --password-stdin

build-api:
  stage: build api
  script:
    - docker build -t justus1994/hungryhoneybadgerapi ./api
    - docker push justus1994/hungryhoneybadgerapi
  only:
    - master

build-client:
  stage: build client
  script:
    - docker build -t justus1994/hungryhoneybadgerclient ./web
    - docker push justus1994/hungryhoneybadgerclient
  only:
    - master
