image: docker:latest
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - test
  - deploy

test:
  image: golang:alpine
  stage: test
  services: 
    - redis:latest
  script:
    - apk update && apk add --no-cache git
    - cd api && go mod download
    - CGO_ENABLED=0 go test

deploy:
  stage: deploy
  script:
    - docker info
    - echo "$REGISTRY_PWD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker pull justus1994/dev4cloud:latest
    - docker build --cache-from justus1994/dev4cloud:latest -t justus1994/dev4cloud:latest ./api
    - docker push justus1994/dev4cloud
  only:
    - master
