image: docker:latest
variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - build api

test-api:
  image: golang:alpine
  stage: test api
  services: 
    - redis:latest
  script:
    - apk update && apk add --no-cache git
    - cd api && go mod download
    - CGO_ENABLED=0 go test

before_script:
  - docker info
  - echo "$REGISTRY_PWD" | docker login -u "$REGISTRY_USER" --password-stdin

build-api:
  stage: build api
  script:
    - docker pull justus1994/private:latest
    - docker build --cache-from justus1994/private:latest -t justus1994/private:latest ./api
    - docker push justus1994/private
  only:
    - master
