image: docker:latest

services:
  - docker:dind

stages:
    - build
    - push
    
before_script:
   - docker info
   - echo "$REGISTRY_PWD" | docker login --username "$REGISTRY_USER" --password-stdin

build-master:
  stage: build
  script:
    - docker info 
    - docker build -t "$REGISTRY_IMAGE" -t "$MAJOR_VERSION".
  only:
    - master

push-master:
   stage: push
   script:
     - docker push "$REGISTRY_IMAGE" 
   only:
     - master
