version: "3"

services:
  reverseproxy:
    image: nginx:alpine
    depends_on:
      - frontend
      - api
    ports:
      - "8080:8080"
    volumes:
      - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf
  api:
    build:
      context: ./api
    depends_on:
      - redis
  redis:
    image: redis:alpine
  frontend:
    build:
      context: ./web
