version: "3"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile_test
    depends_on:
      - redis
    environment:
      - HUNGRYHONEYDOCKER=true
      - UNSPLASH_API_KEY
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
