version: "3"

services:
  reverseproxy:
    image: nginx:alpine
    depends_on:
      - frontend
      - api
    ports:
      - "8080:8080"
    volumes:
      - ./reverseproxy/nginx.conf:/etc/nginx/nginx.conf
  api:
    image: justus1994/hungryhoneybadgerapi
    depends_on:
      - redis
    environment:
      - HUNGRYHONEYDOCKER=true
      - UNSPLASH_API_KEY
  redis:
    image: redis:alpine
  frontend:
    image: justus1994/hungryhoneybadgerclient
